In [7]:
import numpy as np
np.random.seed(111)
np.random.sample((3,4))

array([[0.61217018, 0.16906975, 0.43605902, 0.76926247],
       [0.2953253 , 0.14916296, 0.02247832, 0.42022449],
       [0.23868214, 0.33765619, 0.99071246, 0.23772645]])

In [2]:
np.random.randint(10,100,(2,3))

array([[82, 47, 86],
       [68, 22, 55]], dtype=int32)

In [3]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [5]:
np.arange(10,20).reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
# linearly spaced values
arr=np.linspace(10,20,5)

In [12]:
#  indexing in numpy
arrys=np.random.randint(10,100,size=(4,5))

In [13]:
arrys[:,:]

array([[71, 55, 58, 44, 71],
       [51, 42, 92, 17, 15],
       [30, 17, 13, 56, 58],
       [44, 38, 92, 82, 87]], dtype=int32)

In [16]:
arrys[[0,3],:]

array([[71, 55, 58, 44, 71],
       [44, 38, 92, 82, 87]], dtype=int32)

In [ ]:
arrys[[0,3],:]

In [1]:
# elementwise operation on arrays
l=list(range(10,20))
print(l)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [4]:
array=list(map(lambda x:x+10,l))
print(array)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

In [15]:
# matrix multiplication
import numpy as np
mat1=np.matrix([[1,2,3],[4,5,6]])
mat1.shape

(2, 3)

In [16]:
mat2=np.matrix([[5,3,5],[8,9,7]])
mat2.shape

(2, 3)

In [17]:
mat3=mat2.T
mat3.shape

(3, 2)

In [18]:
mat1*mat3

matrix([[ 26,  47],
        [ 65, 119]])

In [21]:
# Aggregation operations
mat1.sum()
mat1.mean()

np.float64(3.5)

In [ ]:
# Axis wise
mat1
mat1.sum(axis=1) #here 1 is row and 0 is column

matrix([[ 6],
        [15]])

In [ ]:
np.vsplit(mat1,2) # row level splitting
np.hsplit(mat1,2) # column level splitting

[matrix([[1, 2, 3]]), matrix([[4, 5, 6]])]

In [ ]:
#  stacking
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
np.vstack([a,b]) # it merges it it has same no of coloumns

array([[1, 2],
       [3, 4],
       [5, 6]])

 Pandass
 -->it is used for data wraganling-data transformation
 -->Data manipulation and analysis
 2 important ds
 1) Series--1D of pandas--simmilar to the eqvivalent to numpy vectors
 --u will be able to access the index 
 --if i use list with the large number of data it will buffer but with series it will not buffer
 2) data Frame--2D of pandas--excel/db

In [30]:
# series
%pip install pandas
import pandas as pd
s = pd.Series([1, 23, "pu", 7.3])
s#  series

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting pandas
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in c:\users\conbi_g\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2.4.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\conbi_g\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\conbi_g\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.9 MB 5.7 MB/s eta 0:00:02
   -------------- ------------------------- 3.7/9.9 MB 9.4 MB/s eta 0:00:01
   ------------------------- -------------- 6.3/9.9 MB 10.5 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/9.9 MB 9.8 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 7.3 MB/s  0:00:01
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.3 tzdata-2026.2
Note: you may need to restart the kernel to use updated packages.

0      1
1     23
2     pu
3    7.3
dtype: object

object-categorical-alpha numeric
int/float-numerical
dateTime-Date and Time

In [34]:
l=pd.array([1,2,54,23,12,4])
print(l)

<IntegerArray>
[1, 2, 54, 23, 12, 4]
Length: 6, dtype: Int64

In [35]:
s=pd.Series(l)
s

0     1
1     2
2    54
3    23
4    12
5     4
dtype: Int64

In [37]:
s = pd.Series([1, 23, "pu", 7.3,True],index=list("ABCDE"))
s

A       1
B      23
C      pu
D     7.3
E    True
dtype: object

In [38]:
np.random.randint(10,100,(10,5))

array([[82, 47, 86, 68, 22],
       [55, 79, 88, 41, 98],
       [80, 23, 60, 96, 78],
       [39, 19, 52, 29, 48],
       [69, 98, 14, 27, 84],
       [21, 59, 98, 88, 16],
       [55, 69, 82, 74, 11],
       [19, 22, 13, 55, 47],
       [79, 79, 43, 42, 17],
       [64, 53, 88, 81, 60]], dtype=int32)

In [42]:
sample=pd.DataFrame(np.random.randint(10,100,(10,5)),columns=list("ABCDE"))
sample

    A   B   C   D   E
0  43  71  27  41  37
1  78  86  66  53  21
2  33  45  61  87  89
3  58  82  69  23  43
4  76  51  61  71  65
5  38  46  19  43  88
6  35  80  18  43  72
7  97  77  45  83  65
8  23  69  30  98  71
9  94  30  66  16  95

In [45]:
df1=pd.DataFrame({"Name":['A','B',"C","D","E","F"],"Marks":[10,11,12,13,14,15]})

df1

  Name  Marks
0    A     10
1    B     11
2    C     12
3    D     13
4    E     14
5    F     15

In [46]:
# File Handling
import os

In [48]:
os.getcwd()
os.listdir()

['.git',
 'dsfs',
 'handson.py',
 'numpy_hands.py',
 'numpy_handson.ipynb',
 'numpy_pandas_handson.ipynb',
 'polymorphism.py',
 'practise.py',
 'problem1.py',
 'problem2.py']

In [51]:
df_csv=pd.read_csv("Sales CSV.csv")
df_csv.head(2)

  Name  Age  Salary
0    M   98      22
1    N   19      55

In [53]:
df_csv.shape

(999, 3)

In [ ]:
df_ex=pd.read_excel(r"")# it will conver the gaps as a string and not as a special character
df_ex

In [58]:
%pip install openpyxl
dfv=pd.read_excel("PropertyOrderProduct.xlsx",sheet_name=None)
dfv

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

{'PropertyInfo':     PropertyID   PropertyCity  PropertyState
 0            1       New York       New York
 1            2     Cincinnati           Ohio
 2            3       Portland         Oregon
 3            4        Seattle     Washington
 4            5    Kansas City       Missouri
 5            6        Orlando        Florida
 6            7         Boston  Massachusetts
 7            8   Philadelphia   Pennsylvania
 8            9       Richmond       Virginia
 9           10      Arlington       Virginia
 10          11        Atlanta        Georgia
 11          12         Dallas          Texas
 12          13    New Orleans      Louisiana
 13          14      Nashville      Tennessee
 14          15        Chicago       Illinois
 15          16         Denver       Colorado
 16          17      Las Vegas         Nevada
 17          18        Phoenix        Arizona
 18          19    Los Angeles     California
 19          20  San Francisco     California,
 'Products':     ProductID   ProductName ProductCategory  Price
 0           1   Large Towel    Housekeeping      9
 1           2    Hand Towel    Housekeeping      5
 2           3     Washcloth    Housekeeping      3
 3           4       Shampoo    Housekeeping     40
 4           5   Moisturizer    Housekeeping     40
 ..        ...           ...             ...    ...
 89         90  Luggage Cart    Public Areas    138
 90         91    Small Sign    Public Areas     14
 91         92    Large Sign    Public Areas     20
 92         93      Terminal    Public Areas     85
 93         94       Monitor    Public Areas     70

 [94 rows x 4 columns],
 'OrderDetails':       OrderID  OrderDate  PropertyID  ProductID  Quantity
 0           1 2015-01-01          17         41         1
 1           2 2015-01-01          15         54         2
 2           3 2015-01-01           5         71         2
 3           4 2015-01-01          19          3         2
 4           5 2015-01-01          12         45         3
 ...       ...        ...         ...        ...       ...
 4995     4996 2016-12-31           3         47         2
 4996     4997 2016-12-31          12         57         1
 4997     4998 2016-12-31           7         77         1
 4998     4999 2016-12-31          17         57         1
 4999     5000 2016-12-31           1          9         2

 [5000 rows x 5 columns]}

In [56]:
os.listdir()

['.git',
 'dsfs',
 'handson.py',
 'numpy_hands.py',
 'numpy_handson.ipynb',
 'numpy_pandas_handson.ipynb',
 'polymorphism.py',
 'practise.py',
 'problem1.py',
 'problem2.py',
 'PropertyOrderProduct.xlsx',
 'Sales CSV.csv']

In [60]:
dfv.keys()

dict_keys(['PropertyInfo', 'Products', 'OrderDetails'])

In [61]:
props=dfv["PropertyInfo"]
prods=dfv["Products"]
ords=dfv["OrderDetails"]

In [62]:
sample

    A   B   C   D   E
0  43  71  27  41  37
1  78  86  66  53  21
2  33  45  61  87  89
3  58  82  69  23  43
4  76  51  61  71  65
5  38  46  19  43  88
6  35  80  18  43  72
7  97  77  45  83  65
8  23  69  30  98  71
9  94  30  66  16  95

In [63]:
df=pd.read_excel("Sales.xlsx")
df.columns

Index(['OrderID', 'OrderDate', 'PropertyID', 'ProductID', 'Quantity',
       'ProductName', 'ProductCategory', 'Price', 'PropertyCity',
       'PropertyState', 'sales'],
      dtype='str')

In [64]:
df.info() # meta data

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          5000 non-null   int64
 1   OrderDate        5000 non-null   datetime64[us]
 2   PropertyID       5000 non-null   int64
 3   ProductID        5000 non-null   int64
 4   Quantity         5000 non-null   int64
 5   ProductName      5000 non-null   str
 6   ProductCategory  5000 non-null   str
 7   Price            5000 non-null   int64
 8   PropertyCity     5000 non-null   str
 9   PropertyState    5000 non-null   str
 10  sales            5000 non-null   int64
dtypes: datetime64[us](1), int64(6), str(4)
memory usage: 429.8 KB

In [66]:
df.nunique()

OrderID            5000
OrderDate           731
PropertyID           20
ProductID            94
Quantity              3
ProductName          94
ProductCategory       5
Price                48
PropertyCity         20
PropertyState        18
sales               112
dtype: int64

In [67]:
df['ProductCategory'].unique()

<StringArray>
['Furnishings', 'Maintenance', 'Housekeeping', 'Public Areas',
 'Office Supplies']
Length: 5, dtype: str

In [68]:
df['ProductCategory'].value_counts()

ProductCategory
Furnishings        1368
Public Areas       1101
Housekeeping       1063
Maintenance         804
Office Supplies     664
Name: count, dtype: int64

In [69]:
sample.sort_index(ascending=False)

    A   B   C   D   E
9  94  30  66  16  95
8  23  69  30  98  71
7  97  77  45  83  65
6  35  80  18  43  72
5  38  46  19  43  88
4  76  51  61  71  65
3  58  82  69  23  43
2  33  45  61  87  89
1  78  86  66  53  21
0  43  71  27  41  37

In [70]:
test=df.iloc[:10]
test

,OrderID,OrderDate,PropertyID,ProductID,Quantity,ProductName,ProductCategory,Price,PropertyCity,PropertyState,sales
0,1,2015-01-01,17,41,1,Office Chair,Furnishings,85,Las Vegas,Nevada,85
1,163,2015-01-01,17,41,2,Office Chair,Furnishings,85,Las Vegas,Nevada,170
2,1598,2015-01-01,17,41,3,Office Chair,Furnishings,85,Las Vegas,Nevada,255
3,4155,2015-01-01,17,41,2,Office Chair,Furnishings,85,Las Vegas,Nevada,170
4,1109,2015-01-01,17,54,2,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300
5,2759,2015-01-01,17,54,2,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300
6,1251,2015-01-01,17,71,2,Hammer,Maintenance,17,Las Vegas,Nevada,34
7,4276,2015-01-01,17,71,1,Hammer,Maintenance,17,Las Vegas,Nevada,17
8,1857,2015-09-30,17,3,3,Washcloth,Housekeeping,3,Las Vegas,Nevada,9
9,2659,2016-01-23,17,3,2,Washcloth,Housekeeping,3,Las Vegas,Nevada,6

In [71]:
test.sort_values(by=["ProductName","sales"])

,OrderID,OrderDate,PropertyID,ProductID,Quantity,ProductName,ProductCategory,Price,PropertyCity,PropertyState,sales
4,1109,2015-01-01,17,54,2,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300
5,2759,2015-01-01,17,54,2,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300
7,4276,2015-01-01,17,71,1,Hammer,Maintenance,17,Las Vegas,Nevada,17
6,1251,2015-01-01,17,71,2,Hammer,Maintenance,17,Las Vegas,Nevada,34
0,1,2015-01-01,17,41,1,Office Chair,Furnishings,85,Las Vegas,Nevada,85
1,163,2015-01-01,17,41,2,Office Chair,Furnishings,85,Las Vegas,Nevada,170
3,4155,2015-01-01,17,41,2,Office Chair,Furnishings,85,Las Vegas,Nevada,170
2,1598,2015-01-01,17,41,3,Office Chair,Furnishings,85,Las Vegas,Nevada,255
9,2659,2016-01-23,17,3,2,Washcloth,Housekeeping,3,Las Vegas,Nevada,6
8,1857,2015-09-30,17,3,3,Washcloth,Housekeeping,3,Las Vegas,Nevada,9

In [72]:
# Boolean Indexing
test

,OrderID,OrderDate,PropertyID,ProductID,Quantity,ProductName,ProductCategory,Price,PropertyCity,PropertyState,sales
0,1,2015-01-01,17,41,1,Office Chair,Furnishings,85,Las Vegas,Nevada,85
1,163,2015-01-01,17,41,2,Office Chair,Furnishings,85,Las Vegas,Nevada,170
2,1598,2015-01-01,17,41,3,Office Chair,Furnishings,85,Las Vegas,Nevada,255
3,4155,2015-01-01,17,41,2,Office Chair,Furnishings,85,Las Vegas,Nevada,170
4,1109,2015-01-01,17,54,2,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300
5,2759,2015-01-01,17,54,2,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300
6,1251,2015-01-01,17,71,2,Hammer,Maintenance,17,Las Vegas,Nevada,34
7,4276,2015-01-01,17,71,1,Hammer,Maintenance,17,Las Vegas,Nevada,17
8,1857,2015-09-30,17,3,3,Washcloth,Housekeeping,3,Las Vegas,Nevada,9
9,2659,2016-01-23,17,3,2,Washcloth,Housekeeping,3,Las Vegas,Nevada,6

In [73]:
test[test['sales']>100]

,OrderID,OrderDate,PropertyID,ProductID,Quantity,ProductName,ProductCategory,Price,PropertyCity,PropertyState,sales
1,163,2015-01-01,17,41,2,Office Chair,Furnishings,85,Las Vegas,Nevada,170
2,1598,2015-01-01,17,41,3,Office Chair,Furnishings,85,Las Vegas,Nevada,255
3,4155,2015-01-01,17,41,2,Office Chair,Furnishings,85,Las Vegas,Nevada,170
4,1109,2015-01-01,17,54,2,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300
5,2759,2015-01-01,17,54,2,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300

In [ ]:
# Indexing -slicing and dicing the data

In [74]:
array.my_array=np.array([[[[1,3,4]]]])

AttributeError: 'list' object has no attribute 'my_array' and no __dict__ for setting new attributes

In [76]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))

a

array([[[[  0,   1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10,  11],
         [ 12,  13,  14,  15,  16,  17],
         [ 18,  19,  20,  21,  22,  23],
         [ 24,  25,  26,  27,  28,  29]],

        [[ 30,  31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40,  41],
         [ 42,  43,  44,  45,  46,  47],
         [ 48,  49,  50,  51,  52,  53],
         [ 54,  55,  56,  57,  58,  59]],

        [[ 60,  61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70,  71],
         [ 72,  73,  74,  75,  76,  77],
         [ 78,  79,  80,  81,  82,  83],
         [ 84,  85,  86,  87,  88,  89]],

        [[ 90,  91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100, 101],
         [102, 103, 104, 105, 106, 107],
         [108, 109, 110, 111, 112, 113],
         [114, 115, 116, 117, 118, 119]]],


       [[[120, 121, 122, 123, 124, 125],
         [126, 127, 128, 129, 130, 131],
         [132, 133, 134, 135, 136, 137],
         [138, 139, 140, 141, 142, 143],
         [144, 145, 146, 147, 148, 149]],

        [[150, 151, 152, 153, 154, 155],
         [156, 157, 158, 159, 160, 161],
         [162, 163, 164, 165, 166, 167],
         [168, 169, 170, 171, 172, 173],
         [174, 175, 176, 177, 178, 179]],

        [[180, 181, 182, 183, 184, 185],
         [186, 187, 188, 189, 190, 191],
         [192, 193, 194, 195, 196, 197],
         [198, 199, 200, 201, 202, 203],
         [204, 205, 206, 207, 208, 209]],

        [[210, 211, 212, 213, 214, 215],
         [216, 217, 218, 219, 220, 221],
         [222, 223, 224, 225, 226, 227],
         [228, 229, 230, 231, 232, 233],
         [234, 235, 236, 237, 238, 239]]],


       [[[240, 241, 242, 243, 244, 245],
         [246, 247, 248, 249, 250, 251],
         [252, 253, 254, 255, 256, 257],
         [258, 259, 260, 261, 262, 263],
         [264, 265, 266, 267, 268, 269]],

        [[270, 271, 272, 273, 274, 275],
         [276, 277, 278, 279, 280, 281],
         [282, 283, 284, 285, 286, 287],
         [288, 289, 290, 291, 292, 293],
         [294, 295, 296, 297, 298, 299]],

        [[300, 301, 302, 303, 304, 305],
         [306, 307, 308, 309, 310, 311],
         [312, 313, 314, 315, 316, 317],
         [318, 319, 320, 321, 322, 323],
         [324, 325, 326, 327, 328, 329]],

        [[330, 331, 332, 333, 334, 335],
         [336, 337, 338, 339, 340, 341],
         [342, 343, 344, 345, 346, 347],
         [348, 349, 350, 351, 352, 353],
         [354, 355, 356, 357, 358, 359]]]])

In [79]:
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
b

array([[[[359, 358, 357],
         [356, 355, 354],
         [353, 352, 351],
         [350, 349, 348],
         [347, 346, 345],
         [344, 343, 342]],

        [[341, 340, 339],
         [338, 337, 336],
         [335, 334, 333],
         [332, 331, 330],
         [329, 328, 327],
         [326, 325, 324]],

        [[323, 322, 321],
         [320, 319, 318],
         [317, 316, 315],
         [314, 313, 312],
         [311, 310, 309],
         [308, 307, 306]],

        [[305, 304, 303],
         [302, 301, 300],
         [299, 298, 297],
         [296, 295, 294],
         [293, 292, 291],
         [290, 289, 288]]],


       [[[287, 286, 285],
         [284, 283, 282],
         [281, 280, 279],
         [278, 277, 276],
         [275, 274, 273],
         [272, 271, 270]],

        [[269, 268, 267],
         [266, 265, 264],
         [263, 262, 261],
         [260, 259, 258],
         [257, 256, 255],
         [254, 253, 252]],

        [[251, 250, 249],
         [248, 247, 246],
         [245, 244, 243],
         [242, 241, 240],
         [239, 238, 237],
         [236, 235, 234]],

        [[233, 232, 231],
         [230, 229, 228],
         [227, 226, 225],
         [224, 223, 222],
         [221, 220, 219],
         [218, 217, 216]]],


       [[[215, 214, 213],
         [212, 211, 210],
         [209, 208, 207],
         [206, 205, 204],
         [203, 202, 201],
         [200, 199, 198]],

        [[197, 196, 195],
         [194, 193, 192],
         [191, 190, 189],
         [188, 187, 186],
         [185, 184, 183],
         [182, 181, 180]],

        [[179, 178, 177],
         [176, 175, 174],
         [173, 172, 171],
         [170, 169, 168],
         [167, 166, 165],
         [164, 163, 162]],

        [[161, 160, 159],
         [158, 157, 156],
         [155, 154, 153],
         [152, 151, 150],
         [149, 148, 147],
         [146, 145, 144]]],


       [[[143, 142, 141],
         [140, 139, 138],
         [137, 136, 135],
         [134, 133, 132],
         [131, 130, 129],
         [128, 127, 126]],

        [[125, 124, 123],
         [122, 121, 120],
         [119, 118, 117],
         [116, 115, 114],
         [113, 112, 111],
         [110, 109, 108]],

        [[107, 106, 105],
         [104, 103, 102],
         [101, 100,  99],
         [ 98,  97,  96],
         [ 95,  94,  93],
         [ 92,  91,  90]],

        [[ 89,  88,  87],
         [ 86,  85,  84],
         [ 83,  82,  81],
         [ 80,  79,  78],
         [ 77,  76,  75],
         [ 74,  73,  72]]],


       [[[ 71,  70,  69],
         [ 68,  67,  66],
         [ 65,  64,  63],
         [ 62,  61,  60],
         [ 59,  58,  57],
         [ 56,  55,  54]],

        [[ 53,  52,  51],
         [ 50,  49,  48],
         [ 47,  46,  45],
         [ 44,  43,  42],
         [ 41,  40,  39],
         [ 38,  37,  36]],

        [[ 35,  34,  33],
         [ 32,  31,  30],
         [ 29,  28,  27],
         [ 26,  25,  24],
         [ 23,  22,  21],
         [ 20,  19,  18]],

        [[ 17,  16,  15],
         [ 14,  13,  12],
         [ 11,  10,   9],
         [  8,   7,   6],
         [  5,   4,   3],
         [  2,   1,   0]]]])

In [88]:
np.dot(a,b)[2,3,2,1,2,2]

np.int64(499128)

In [87]:
arr=np.array([1,2,3,4,5])
arr.shape[:-1]

()

In [89]:
a=np.array([2,3,4],dtype=complex)
print(a)

[2.+0.j 3.+0.j 4.+0.j]

In [92]:
np.random.seed(100)
a=np.random.uniform(1,50,20)
a

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

In [94]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [95]:
test

,OrderID,OrderDate,PropertyID,ProductID,Quantity,ProductName,ProductCategory,Price,PropertyCity,PropertyState,sales
0,1,2015-01-01,17,41,1,Office Chair,Furnishings,85,Las Vegas,Nevada,85
1,163,2015-01-01,17,41,2,Office Chair,Furnishings,85,Las Vegas,Nevada,170
2,1598,2015-01-01,17,41,3,Office Chair,Furnishings,85,Las Vegas,Nevada,255
3,4155,2015-01-01,17,41,2,Office Chair,Furnishings,85,Las Vegas,Nevada,170
4,1109,2015-01-01,17,54,2,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300
5,2759,2015-01-01,17,54,2,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300
6,1251,2015-01-01,17,71,2,Hammer,Maintenance,17,Las Vegas,Nevada,34
7,4276,2015-01-01,17,71,1,Hammer,Maintenance,17,Las Vegas,Nevada,17
8,1857,2015-09-30,17,3,3,Washcloth,Housekeeping,3,Las Vegas,Nevada,9
9,2659,2016-01-23,17,3,2,Washcloth,Housekeeping,3,Las Vegas,Nevada,6

In [97]:
test.shape

(10, 11)

In [98]:
test["Table_name"]="reatil store"
test

,OrderID,OrderDate,PropertyID,ProductID,Quantity,ProductName,ProductCategory,Price,PropertyCity,PropertyState,sales,Table_name
0,1,2015-01-01,17,41,1,Office Chair,Furnishings,85,Las Vegas,Nevada,85,reatil store
1,163,2015-01-01,17,41,2,Office Chair,Furnishings,85,Las Vegas,Nevada,170,reatil store
2,1598,2015-01-01,17,41,3,Office Chair,Furnishings,85,Las Vegas,Nevada,255,reatil store
3,4155,2015-01-01,17,41,2,Office Chair,Furnishings,85,Las Vegas,Nevada,170,reatil store
4,1109,2015-01-01,17,54,2,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300,reatil store
5,2759,2015-01-01,17,54,2,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300,reatil store
6,1251,2015-01-01,17,71,2,Hammer,Maintenance,17,Las Vegas,Nevada,34,reatil store
7,4276,2015-01-01,17,71,1,Hammer,Maintenance,17,Las Vegas,Nevada,17,reatil store
8,1857,2015-09-30,17,3,3,Washcloth,Housekeeping,3,Las Vegas,Nevada,9,reatil store
9,2659,2016-01-23,17,3,2,Washcloth,Housekeeping,3,Las Vegas,Nevada,6,reatil store

In [99]:
test.loc[:,"new Column"]=list(range(10,20))

test

,OrderID,OrderDate,PropertyID,ProductID,Quantity,ProductName,ProductCategory,Price,PropertyCity,PropertyState,sales,Table_name,new Column
0,1,2015-01-01,17,41,1,Office Chair,Furnishings,85,Las Vegas,Nevada,85,reatil store,10
1,163,2015-01-01,17,41,2,Office Chair,Furnishings,85,Las Vegas,Nevada,170,reatil store,11
2,1598,2015-01-01,17,41,3,Office Chair,Furnishings,85,Las Vegas,Nevada,255,reatil store,12
3,4155,2015-01-01,17,41,2,Office Chair,Furnishings,85,Las Vegas,Nevada,170,reatil store,13
4,1109,2015-01-01,17,54,2,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300,reatil store,14
5,2759,2015-01-01,17,54,2,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300,reatil store,15
6,1251,2015-01-01,17,71,2,Hammer,Maintenance,17,Las Vegas,Nevada,34,reatil store,16
7,4276,2015-01-01,17,71,1,Hammer,Maintenance,17,Las Vegas,Nevada,17,reatil store,17
8,1857,2015-09-30,17,3,3,Washcloth,Housekeeping,3,Las Vegas,Nevada,9,reatil store,18
9,2659,2016-01-23,17,3,2,Washcloth,Housekeeping,3,Las Vegas,Nevada,6,reatil store,19

In [100]:
test.insert(5,column="test",value=test["Quantity"]*test["Price"]) 

test

,OrderID,OrderDate,PropertyID,ProductID,Quantity,test,ProductName,ProductCategory,Price,PropertyCity,PropertyState,sales,Table_name,new Column
0,1,2015-01-01,17,41,1,85,Office Chair,Furnishings,85,Las Vegas,Nevada,85,reatil store,10
1,163,2015-01-01,17,41,2,170,Office Chair,Furnishings,85,Las Vegas,Nevada,170,reatil store,11
2,1598,2015-01-01,17,41,3,255,Office Chair,Furnishings,85,Las Vegas,Nevada,255,reatil store,12
3,4155,2015-01-01,17,41,2,170,Office Chair,Furnishings,85,Las Vegas,Nevada,170,reatil store,13
4,1109,2015-01-01,17,54,2,300,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300,reatil store,14
5,2759,2015-01-01,17,54,2,300,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300,reatil store,15
6,1251,2015-01-01,17,71,2,34,Hammer,Maintenance,17,Las Vegas,Nevada,34,reatil store,16
7,4276,2015-01-01,17,71,1,17,Hammer,Maintenance,17,Las Vegas,Nevada,17,reatil store,17
8,1857,2015-09-30,17,3,3,9,Washcloth,Housekeeping,3,Las Vegas,Nevada,9,reatil store,18
9,2659,2016-01-23,17,3,2,6,Washcloth,Housekeeping,3,Las Vegas,Nevada,6,reatil store,19

In [103]:
test.drop(columns=["test"],inplace=True)
test

,OrderID,OrderDate,PropertyID,ProductID,Quantity,ProductName,ProductCategory,Price,PropertyCity,PropertyState,sales,Table_name,new Column
0,1,2015-01-01,17,41,1,Office Chair,Furnishings,85,Las Vegas,Nevada,85,reatil store,10
1,163,2015-01-01,17,41,2,Office Chair,Furnishings,85,Las Vegas,Nevada,170,reatil store,11
2,1598,2015-01-01,17,41,3,Office Chair,Furnishings,85,Las Vegas,Nevada,255,reatil store,12
3,4155,2015-01-01,17,41,2,Office Chair,Furnishings,85,Las Vegas,Nevada,170,reatil store,13
4,1109,2015-01-01,17,54,2,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300,reatil store,14
5,2759,2015-01-01,17,54,2,Chest of Drawers,Furnishings,150,Las Vegas,Nevada,300,reatil store,15
6,1251,2015-01-01,17,71,2,Hammer,Maintenance,17,Las Vegas,Nevada,34,reatil store,16
7,4276,2015-01-01,17,71,1,Hammer,Maintenance,17,Las Vegas,Nevada,17,reatil store,17
8,1857,2015-09-30,17,3,3,Washcloth,Housekeeping,3,Las Vegas,Nevada,9,reatil store,18
9,2659,2016-01-23,17,3,2,Washcloth,Housekeeping,3,Las Vegas,Nevada,6,reatil store,19